Update the editing .bash_profile behavior.

diff --git a/pygitrepo/{{ repo_name }}/Makefile b/pygitrepo/{{ repo_name }}/Makefile
--- a/pygitrepo/{{ repo_name }}/Makefile
+++ b/pygitrepo/{{ repo_name }}/Makefile
@@ -133,6 +133,7 @@ ifeq (${DETECTED_OS}, Linux)
     OPEN_COMMAND="open"
 endif
 
+PROFILE_FILE = "${HOME}/.bash_profile"
 
 BIN_ACTIVATE="${BIN_DIR}/activate"
 BIN_PYTHON="${BIN_DIR}/python"
@@ -150,15 +151,15 @@ PY_VERSION="${PY_VER_MAJOR}.${PY_VER_MINOR}.${PY_VER_MICRO}"
 
 
 .PHONY: help
-help: ## Show this help message
+help: ## ** Show this help message
 	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
 
 
 #--- Make Commands ---
 .PHONY: info
-info: ## Show information about python, pip in this environment
+info: ## ** Show information about python, pip in this environment
 	@echo - venv: ${VENV_DIR_REAL} "\n"
-	@echo - python executable: ${BIN_PYTHON} "\n"
+	@echo - python exe®cutable: ${BIN_PYTHON} "\n"
 	@echo - pip executable: ${BIN_PIP} "\n"
 	@echo - document: ${DOC_URL} "\n"
 	@echo - site-packages: ${SITE_PACKAGES} "\n"
@@ -171,14 +172,24 @@ brew_install_pyenv: ## Install pyenv and pyenv-virtualenv
 	-brew install pyenv-virtualenv
 
 
-.PHONY: setup_pyenv
-setup_pyenv: brew_install_pyenv ## Do some pre-setup for pyenv and pyenv-virtualenv
-	-rm ~/.bash_profile
-	echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.bash_profile
-	echo 'export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.bash_profile
-	echo 'eval "$$(pyenv init -)"' >> ~/.bash_profile
-	echo 'eval "$$(pyenv virtualenv-init -)"' >> ~/.bash_profile
+.PHONY: enable_pyenv
+enable_pyenv: ## Config $HOME/.bash_profile file
+	if ! grep -q 'export PYENV_ROOT="$$HOME/.pyenv"' "${PROFILE_FILE}" ; then\
+	    echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> "${PROFILE_FILE}" ;\
+	fi
+	if ! grep -q 'export PATH="$$PYENV_ROOT/bin:$$PATH"' "${PROFILE_FILE}" ; then\
+	    echo 'export PATH="$$PYENV_ROOT/bin:$$PATH"' >> "${PROFILE_FILE}" ;\
+	fi
+	if ! grep -q 'eval "$$(pyenv init -)"' "${PROFILE_FILE}" ; then\
+	    echo 'eval "$$(pyenv init -)"' >> "${PROFILE_FILE}" ;\
+	fi
+	if ! grep -q 'eval "$$(pyenv virtualenv-init -)"' "${PROFILE_FILE}" ; then\
+	    echo 'eval "$$(pyenv virtualenv-init -)"' >> "${PROFILE_FILE}" ;\
+	fi
 
+
+.PHONY: setup_pyenv
+setup_pyenv: brew_install_pyenv enable_pyenv ## Do some pre-setup for pyenv and pyenv-virtualenv
 	pyenv install ${PY_VERSION} -s
 	pyenv rehash
 
@@ -190,12 +201,19 @@ ifeq (${USE_PYENV}, "Y")
 	-brew install pyenv
 	-brew install pyenv-virtualenv
 
-	# Initiate Config File
-	-rm ~/.bash_profile
-	echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.bash_profile
-	echo 'export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.bash_profile
-	echo 'eval "$$(pyenv init -)"' >> ~/.bash_profile
-	echo 'eval "$$(pyenv virtualenv-init -)"' >> ~/.bash_profile
+	# Edit Config File
+	if ! grep -q 'export PYENV_ROOT="$$HOME/.pyenv"' "${PROFILE_FILE}" ; then\
+	    echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> "${PROFILE_FILE}" ;\
+	fi
+	if ! grep -q 'export PATH="$$PYENV_ROOT/bin:$$PATH"' "${PROFILE_FILE}" ; then\
+	    echo 'export PATH="$$PYENV_ROOT/bin:$$PATH"' >> "${PROFILE_FILE}" ;\
+	fi
+	if ! grep -q 'eval "$$(pyenv init -)"' "${PROFILE_FILE}" ; then\
+	    echo 'eval "$$(pyenv init -)"' >> "${PROFILE_FILE}" ;\
+	fi
+	if ! grep -q 'eval "$$(pyenv virtualenv-init -)"' "${PROFILE_FILE}" ; then\
+	    echo 'eval "$$(pyenv virtualenv-init -)"' >> "${PROFILE_FILE}" ;\
+	fi
 
 	pyenv install ${PY_VERSION} -s
 	pyenv rehash
@@ -207,11 +225,11 @@ endif
 
 
 .PHONY: up
-up: init_venv ## Set Up the Virtual Environment
+up: init_venv ## ** Set Up the Virtual Environment
 
 
 .PHONY: clean
-clean: ## Clean Up Virtual Environment
+clean: ## ** Clean Up Virtual Environment
 ifeq (${USE_PYENV}, "Y")
 	-pyenv uninstall -f ${VENV_NAME}
 else
@@ -221,17 +239,17 @@ endif
 
 #--- Install ---
 .PHONY: uninstall
-uninstall: ## Uninstall This Package
+uninstall: ## ** Uninstall This Package
 	-${BIN_PIP} uninstall -y ${PACKAGE_NAME}
 
 
 .PHONY: install
-install: uninstall ## Install This Package via setup.py
+install: uninstall ## ** Install This Package via setup.py
 	${BIN_PIP} install .
 
 
 .PHONY: dev_install
-dev_install: uninstall ## Install This Package in Editable Mode
+dev_install: uninstall ## ** Install This Package in Editable Mode
 	${BIN_PIP} install --editable .
 
 
@@ -252,17 +270,17 @@ doc_dep: ## Install Doc Dependencies
 
 #--- Test ---
 .PHONY: test
-test: dev_install test_dep ## Run test
+test: dev_install test_dep ## ** Run test
 	${BIN_PYTEST} tests -s
 
 
 .PHONY: cov
-cov: dev_install test_dep ## Run Code Coverage test
+cov: dev_install test_dep ## ** Run Code Coverage test
 	${BIN_PYTEST} tests -s --cov=${PACKAGE_NAME} --cov-report term --cov-report annotate:.coverage.annotate
 
 
 .PHONY: tox
-tox: test_dep ## Run tox
+tox: test_dep ## ** Run tox
 	${BIN_PIP} install tox
 	( \
 		pyenv local {{ supported_py_ver|join(" ") }}; \
@@ -280,7 +298,7 @@ init_doc: doc_dep ## Initialize Sphinx Documentation Library
 
 
 .PHONY: build_doc
-build_doc: doc_dep dev_install ## Build Documents, force Update
+build_doc: doc_dep dev_install ## ** Build Documents, force Update
 	${BIN_PYTHON} ./docs/create_doctree.py
 	( \
 		source ${BIN_ACTIVATE}; \
@@ -300,12 +318,12 @@ build_doc_again: dev_install ## Build Documents, Don't Check Dependencies
 
 
 .PHONY: view_doc
-view_doc: ## Open Documents
+view_doc: ## ** Open Documents
 	${OPEN_COMMAND} ./docs/build/html/index.html
 
 
 .PHONY: deploy_doc
-deploy_doc: ## Deploy Document to AWS S3
+deploy_doc: ## ** Deploy Document to AWS S3
 	aws s3 rm ${S3_PREFIX} --recursive
 	aws s3 sync ./docs/build/html ${S3_PREFIX}
 
@@ -316,12 +334,12 @@ clean_doc: ## Clean Existing Documents
 
 
 .PHONY: reformat
-reformat: dev_dep ## Pep8 Format Source Code
+reformat: dev_dep ## ** Pep8 Format Source Code
 	${BIN_PYTHON} fixcode.py
 
 
 .PHONY: publish
-publish: dev_dep ## Publish This Library to PyPI
+publish: dev_dep ## ** Publish This Library to PyPI
 	${BIN_PYTHON} setup.py sdist bdist_wheel
 	${BIN_TWINE} upload dist/*
 	-rm -rf build dist .egg ${PACKAGE_NAME}.egg-info
